buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
    }
    dependencies {
        classpath 'com.anatawa12.forge:ForgeGradle:1.2-1.1.1'
    }
}

apply plugin: 'forge'
apply from: "gradle/scripts/getbuildnumber.gradle"


minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "eclipse/assets"
    replace "@MAJOR@", version_major
    replace "@MINOR@", version_minor
    replace "@REVIS@", version_revis
    replace "@BUILD@", project.getBuildNumber()
}


apply from: "gradle/scripts/jars.gradle"
apply from: "gradle/scripts/version.gradle"

group= "zmaster587.libVulpes" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "LibVulpes-Continuation"
sourceCompatibility = 8
targetCompatibility = 8

clean {
    delete 'output'
}


repositories {
    maven {
        name = "chickenbones"
        url = "https://chickenbones.net/maven/"
    }
    ivy {
        name "industrialcraft-2"
        artifactPattern "https://jenkins.ic2.player.to/job/IC2_experimental/827/artifact/build/libs/[module]-[revision].[ext]"
    }
}

dependencies {
    // you may put jars on which you depend on in ./libs
    // or you may define them like so..
    //compile "some.group:artifact:version:classifier"
    //compile "some.group:artifact:version"
      
    // real examples
    //compile 'com.mod-buildcraft:buildcraft:7.0.20:dev'  // adds buildcraft to the dev env
    implementation 'codechicken:CodeChickenLib:1.7.10-1.1.3.127:dev'
    implementation 'codechicken:CodeChickenCore:1.7.10-1.0.4.35:dev'
    implementation 'codechicken:NotEnoughItems:1.7.10-1.0.4.95:dev'
    implementation name: 'industrialcraft-2', version: '2.2.827-experimental-api', ext: 'jar'
    
    // gotta get it manually now, RIP downloading from curseforge, their examples don't even work now
    //compile name: 'CoFHCore', version: '[1.7.10]3.0.3-303', ext: 'jar'
    //compile 'com.googlecode.efficient-java-matrix-library:ejml:0.24' // adds ejml to the dev env

    // for more info...
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html

}

processResources
{
    // This will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // Replace values in only mcmod.info.
    filesMatching('mcmod.info') {
        // Replace version and mcversion.
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
}
